title: "Jorrit Schafer"
email: jorrit.schafer@gmail.com
description: "Associate Director, Advanced Analytics"

remote_theme: LeNPaul/portfolio-jekyll-theme

baseurl: ""
url: "https://yourusername.github.io"

navbar:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
  - title: "About"
    url: "/about/"

plugins:
  - jekyll-feed

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
