# Site basics
title: "Jorrit Schafer"
author: "Jorrit Schafer"
email: jorrit.schafer@example.com
description: "| Healthcare Analytics | Data Science | Storytelling"
url: "https://jorrit-schafer.github.io"
baseurl: ""  # Keep this blank for user site

# Social links (used for icons and SEO)
github_username: jorrit-schafer
linkedin_username: jorritschafer

# Avatar image (ensure file exists at assets/img/avatar.png)
avatar: "/assets/img/avatar.png"

# Navigation bar
navbar_links:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
  - title: "About"
    url: "/aboutme/"
  - title: "Contact"
    url: "/contact/"

# Markdown engine and theme
markdown: kramdown
theme: minima  # or 'jekyll-theme-minimal' if using Pages theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional blog settings
paginate: 5
paginate_path: "/blog/page:num/"
permalink: /:year/:month/:day/:title/

# Defaults (optional, for blog posts)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: "Jorrit Schafer"
      comments: true
      share: true
