# Site settings
title: "Jorrit Schafer"
author: "Jorrit Schafer"
description: "Pharma | Advanced Analytics | Real-World Evidence | Machine Learning"
email: jorrit.schafer@example.com
url: "https://jorrit-schafer.github.io"
baseurl: "" # leave blank for user/organization GitHub Pages site

# Social media usernames
github_username: jorrit-schafer
linkedin_username: jorritschafer

# Avatar image (place this file in assets/img/)
avatar: "/assets/img/avatar.png"

# Navigation bar links
navbar_links:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
  - title: "About"
    url: "/aboutme/"
  - title: "Contact"
    url: "/contact/"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional: Google Analytics (uncomment if using)
# google_analytics: UA-XXXXXXXXX-X
